### ISSUE TITLE
ISSUE!!!!

### ISSUE THREAD

**Issue by EllaKarnikHinks** [LondonRestaurantAPIs/LondonRAPIs#2]
How do we limit the amount of info we are getting from tourpedia?? 
When I try to use a smaller search such a s "Mile End" it says "bad parameter"
Any bright ideas????

**Comment by EllaKarnikHinks** [comment]
:scream_cat:

**Comment by chigbolu** [comment]
Good point! We could narrow down the serach looking for restaurants that contain the word Italian ( of course ;) ) and we will reduce the search response. We could even use the word chinese restaurant , as there are still far too many Italian restaurants in London.

**Comment by chigbolu** [comment]
;)

**Comment by EllaKarnikHinks** [comment]
:wink:

**Comment by EllaKarnikHinks** [comment]
New plan: full steam ahead and if we have problems later, we will sort them then!!!
:fireworks:
